name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t luxshan/trial-ci-cd .
      - name: Publish image to docker hub
        run: docker push luxshan/trial-ci-cd:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull luxshan/trial-ci-cd
      - name: Delete old container
        run: docker rm -f trial-ci-cd-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name trial-ci-cd-container -e REACT_APP_NAME="LUXSHARANY" luxshan/trial-ci-cd

