name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ LuxShan }}
          password: ${{ Luxshan23&27 }}
      - name: Build docker image
        run: docker build -t Luxshan2000/trial-ci-cd .
      - name: Publish image to docker hub
        run: docker push Luxshan2000/trial-ci-cd:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull Luxshan2000/trial-ci-cd:latest
      - name: Delete old container
        run: docker rm -f trial-ci-cd-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name trial-ci-cd-container Luxshan2000/trial-ci-cd
